name: Mark Snowden
favicon: null
layout_spectrum: 0.98623
typography_spectrum: 0.00010737590491771698
title: Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.08233357756398618
  lightness: 0.2506768642924726
  saturation: 0.6277546160854399
  rhythmicContrast: 0.33983020135201514
purpose: []
