analytics: {}
color:
  brandColors:
    - '#A8C0D0'
    - '#406018'
    - '#708898'
    - '#1070C0'
    - '#000000'
  brandStrength: 0.125
  lightness: 0.250676
  rhythmicContrast: 0.5
  saturation: 0.627754
cta: {}
layout_spectrum: 0.792792
name: buzzard
opengraph: {}
purpose: []
typography_spectrum: 0.000107
