name: Mark Snowden
favicon: null
layout_spectrum: 0.74278
typography_spectrum: 0.99549
title: Mark Snowden
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5ebf8'
    - '#a0978e'
    - '#161f28'
    - '#7d746b'
    - '#3d3737'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
