name: Mark Snowden
favicon: null
layout_spectrum: 0.96116
typography_spectrum: 0.99549
title: Mark Snowden
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A8C0D0'
    - '#406018'
    - '#708898'
    - '#1070C0'
    - '#000000'
  brandStrength: 0.25
  lightness: 0.125
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
