name: Mark Snowden
favicon: null
layout_spectrum: 0.99391
typography_spectrum: 0.80579
title: Mark Snowden
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfeff'
    - '#272a3b'
    - '#4b5265'
    - '#777f94'
    - '#afb0b5'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
