name: Mark Snowden
favicon: null
layout_spectrum: 0.88912
typography_spectrum: 0.80579
title: Mark Snowden
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5ebf8'
    - '#a0978e'
    - '#161f28'
    - '#7d746b'
    - '#3d3737'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
