name: Mark Snowden
favicon: null
layout_spectrum: 0.15786
typography_spectrum: 0.80579
title: Mark Snowden
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#25292a'
    - '#7d8ea0'
    - '#59636d'
    - '#9fb5cc'
    - '#f5eee6'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
