name: Mark Snowden
favicon: null
layout_spectrum: 0.75181
typography_spectrum: 0.99549
title: Mark Snowden
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A8C0D0'
    - '#406018'
    - '#708898'
    - '#1070C0'
    - '#000000'
  brandStrength: 0.4375
  lightness: 0.250676
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
